agrocognitive/agrocognitive/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', views.home, name="home"),
    # url(r'^menu/$', views.menuPrincipal, name="menuPrincipal"),
    # url(r'^monitorearCultivos/$', views.monitorearCultivos, name="monitorearCultivos"),
    # url(r'^cultivo/$', views.infoCultivo, name="infoCultivo"),
    # url(r'^estadoCultivo/$', views.estadoCultivo, name="estadoCultivo"),
    # url(r'^cargarImagenes/$', views.cargarImagenes, name="cargarImagenes"),
    # url(r'^generarReporte/$', views.generarReporte, name="generarReporte"),

    # url(r'^cargarZip/$', views.cargarZip, name="cargarZip"),
    url(r'^api/', include('app.api.urls', namespace='api')),

    # url(r'^signup/$', views.signup, name="signup"),
]

agrocognitive/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

app/forms.py
# # -*- coding: utf-8 -*-

from django import forms
from django.core.validators import RegexValidator
from django.forms import ModelChoiceField
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext, ugettext_lazy as _
from django.forms.extras.widgets import SelectDateWidget
import datetime

from app.models import User

# from app.app

class SignUpForm(UserCreationForm):

  first_name = forms.CharField(max_length=30, required=True, label='Nombre')
  last_name = forms.CharField(max_length=30, required=True, label='Apellido')
  # mobile_phone = forms.RegexField(regex=r'^\+?\d{9,15}$', required=True, label="Número de teléfono ( Ej +582125834456 )")
  # address = forms.CharField(max_length=30, required=True, label='Dirección')
  id_number = forms.CharField(max_length=30, required=True, label='Número de identificación')

  def __init__(self, *args, **kwargs):
    super(SignUpForm, self).__init__(*args, **kwargs)
    for i in self.fields:
        self.fields[i].widget.attrs.update({'class' : 'form-control', 'placeholder': self.fields[i].label})
  
  def clean_email(self):
    return self.cleaned_data['email'].lower()
  
  def clean_first_name(self):
    return self.cleaned_data['first_name'].title()
  
  def clean_last_name(self):
    return self.cleaned_data['last_name'].title()

  class Meta:
    model = User
    fields = ('email', 'password1', 'password2', 'first_name', 'last_name', 'id_number')



# class AuthenticationForm(forms.Form):

#   email = forms.EmailField(required=True, label=_(u"Email"))
#   password = forms.CharField(widget=forms.PasswordInput, required=True, label=_(u"Password"))

#   def __init__(self, *args, **kwargs):
#     super(AuthenticationForm, self).__init__(*args, **kwargs)
#     for i in self.fields:
#         self.fields[i].widget.attrs.update({'class' : 'form-control', 'placeholder': self.fields[i].label})


class iniciarSesionForm(forms.Form):
    identificacion = forms.CharField(
                            max_length = 50,
                            required = True,
                            label = "Usuario",
                            widget = forms.TextInput(attrs={'style': 'width:100%'})
                    )

    clave = forms.CharField(
                            max_length = 25,
                            required = True,
                            label = "Contraseña",
                            widget = forms.PasswordInput(attrs={'style': 'width:100%'})
            )


class cargarImagenesVueloForm(forms.Form):
    archivo = forms.FileField(required=True)
    


templates/cargarImagenes.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="keywords" content="">
	<meta name="description" content="">

	<title>Información Cultivo | AgroCognitive</title>

	<!-- stylesheet css -->
	<link rel="stylesheet" href="../static/css/bootstrap.min.css">
	<link rel="stylesheet" href="../static/css/font-awesome.min.css">
	<link rel="stylesheet" href="../static/css/nivo-lightbox.css">
	<link rel="stylesheet" href="../static/css/nivo_themes/default/default.css">
	<link rel="stylesheet" href="../static/css/style.css">
	<!-- google web font css -->
	<link href='http://fonts.googleapis.com/css?family=Raleway:400,300,600,700' rel='stylesheet' type='text/css'>

</head>
<body data-spy="scroll" data-target=".navbar-collapse">
	
<!-- navigation -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon icon-bar"></span>
				<span class="icon icon-bar"></span>
				<span class="icon icon-bar"></span>
			</button>
			<a href="{% url 'menuPrincipal' %}" class="navbar-brand smoothScroll">AgroCognitive</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><a href="#contact" class="smoothScroll">Bienvenida, María</a></li>
				<li>
				<div class="hamburger-btn" onclick="openNav()" style="position: relative;top: 25px; left: 30px;">
						<div></div>
						<div></div>
						<div></div>	
					</div>
				</li>
			</ul>
		</div>
		<div id="mySidenav" class="sidenav">
			  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
			  <a href="#">
			  	<img src="../static/img/cargarImg.png" width="20%" style="margin-right: 10px;">
			  	<h5 style="display: inline-block;">
			  		Cargar imágenes
			  	</h5>
			  </a>
			  <a href="#">
			  	<img src="../static/img/monitorearTerreno.png" width="20%" style="margin-right: 10px;">
			  	<h5 style="display: inline-block;">
			  		Monitorear terrenos
			  	</h5>
			  </a>
			  <a href="#">
			  	<img src="../static/img/monitorearCultivo.png" width="20%" style="margin-right: 10px;">
			  	<h5 style="display: inline-block;">
			  		Monitorear cultivos
			  	</h5>
			  </a>
			  <a href="#">
			  	<img src="../static/img/reporte.png" width="20%" style="margin-right: 10px;">
			  	<h5 style="display: inline-block;">
			  		Generar reportes
			  	</h5>
			  </a>
			  <a href="#">
			  	<img src="../static/img/historico.png" width="20%" style="margin-right: 10px;">
			  	<h5 style="display: inline-block;">
			  		Históricos
			  	</h5>
			  </a>
			</div>
	</div>
</div>		

<!-- service section -->
<div id="cargarImagenes">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 text-center">
				<h2>¿Qué tal estuvo el último vuelo?</h2>
			</div>
		</div>
		<form method="POST" encType="multipart/form-data" name="formPlanVuelo">
			{% csrf_token %}
			<div class="row">
				<br>
				<div class="col-md-5 col-sm-5">
					<!--<i class="fa fa-cubes"></i>-->
					<h4>Selecciona en el mapa el cultivo asociado al plan de vuelo con el que obtuviste las imágenes</h4>
					<div class="icon-bar">
					  <a href="#"><i class="fa fa-search-plus"></i></a> 
					  <a href="#"><i class="fa fa-search-minus"></i></a> 
					  <a href="#"><img class="img-responsive" src="../static/img/grab.png"></a> 
					  <a href="#"><i class="fa fa-expand"></i></a>
					</div>
					<img src="../static/img/mapaTerreno.png" class="img-responsive" width="80%" style="margin-top:20px;">
				</div>
				<div class="col-md-6 col-sm-6 col-md-offset-1 wrapper-cultivo2 text-center">
					<br>
					<h3>Arrastra tus imágenes aquí (*)</h3>
					<br>
					<h4>O si lo prefieres...</h4>
					<br>
					{{ form.archivo }}
					<!-- <div style="position:relative; left:24%;">
						<input type="file" name="archivo" required="" id="id_archivo" onchange="uploadFile()">
					</div>
					<progress id="progressBar" value="0" max="100" style="width:300px;"></progress>
		      <h3 id="status"></h3>
		      <p id="loaded_n_total"></p> -->
					<br><br>
					<h6>(*) Recuerda que las imágenes deben estar en formato PNG o JPG</h6>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 col-sm-4 col-md-offset-4">
					<br>
					&nbsp&nbsp&nbsp<button class="btn btn-warning" type="submit">Enviar imágenes</button>
				</div>
			</div>
		</form>
		<div id="modalImagenes" class="modal fade" role="dialog">
		  <div class="modal-dialog">

		    <!-- Modal content-->
		    <div class="modal-content">	
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal">&times;</button>
		        <h4 class="modal-title">Las imágenes del plan de vuelo han sido procesadas exitosamente</h4>
		      </div>
		      <div class="modal-body">
		        <p>
		        	Ahora que ya enviaste las imágenes de este cultivo puedes elegir repetir el proceso
		        	para otro cultivo de tu terreno o regresar al menú principal.
		        </p>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-warning" data-dismiss="modal" style="float:left;margin-left:-4px;">Otro cultivo</button>
		        <a href="{% url 'menuPrincipal' %}"><button type="button" class="btn btn-warning">Ir al menú</button></a>
		      </div>
		    </div>

		  </div>
		</div>
	</div>
</div>


<!-- divider section -->
<!--<div class="container">
	<div class="row">
		<br><br>
		<div class="col-md-1 col-sm-1"></div>
		<div class="col-md-10 col-sm-10">
			<hr>
		</div>
		<div class="col-md-1 col-sm-1"></div>
	</div>
</div>-->

<!-- footer section -->
<!--<footer>
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 text-center">
				<ul class="list-inline">
                    <li>
                        <a target="_blank" href="https://twitter.com/gia_usb" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                    </li>
                    <li>
                        <a target="_blank" href="https://www.youtube.com/channel/UCfNP1LYdgX3qOONWqjGgGLA" class="btn-social btn-outline"><i class="fa fa-fw fa-youtube"></i></a>
                    </li>
                    <li>
                        <a target="_blank" href="https://github.com/GIA-USB" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                    </li>
                </ul>
				<p>Desarrollado por <a href="https://www.smartbasegroup.com" target="_blank">Smartbase Group</a></p>
			</div>
		</div>
	</div>
</footer>-->


<!-- javascript js -->	
<script src="../static/js/jquery.js"></script>
<script src="../static/js/bootstrap.min.js"></script>	
<script src="../static/js/nivo-lightbox.min.js"></script>
<script src="../static/js/smoothscroll.js"></script>
<script src="../static/js/jquery.nav.js"></script>
<script src="../static/js/isotope.js"></script>
<script src="../static/js/imagesloaded.min.js"></script>
<script src="../static/js/custom.js"></script>
<script type="text/javascript">
	/* Set the width of the side navigation to 250px */
	function openNav() {
	    document.getElementById("mySidenav").style.width = "250px";
	}

	/* Set the width of the side navigation to 0 */
	function closeNav() {
	    document.getElementById("mySidenav").style.width = "0";
	}
</script>
<!-- <script>
	$(document).ready(function(){
		var modalActivo = {{ msg|safe }};
		
		if (modalActivo == "1"){
			$('#modalImagenes').modal("show");
		}
	});
</script> -->
<script type="text/javascript">

	function _(el) {
    return document.getElementById(el);
  }

  function uploadFile() {
    var file = _("id_archivo").files[0];
    var csrf_token = document.getElementsByName('csrfmiddlewaretoken')[0].value
    // alert(file.name+" | "+file.size+" | "+file.type);
    console.log(csrf_token)
    var formdata = new FormData();
    formdata.append("archivo", file);
    formdata.append("csrfmiddlewaretoken", csrf_token);
    var ajax = new XMLHttpRequest();
    ajax.upload.addEventListener("progress", progressHandler, false);
    // ajax.addEventListener("load", completeHandler, false);
    // ajax.addEventListener("error", errorHandler, false);
    // ajax.addEventListener("abort", abortHandler, false);
    ajax.open("POST", "/cargarZip/"); // http://www.developphp.com/video/JavaScript/File-Upload-Progress-Bar-Meter-Tutorial-Ajax-PHP
    //use file_upload_parser.php from above url
    ajax.send(formdata);


  }

  function progressHandler(event) {
    _("loaded_n_total").innerHTML = "Uploaded " + event.loaded + " bytes of " + event.total;
    var percent = (event.loaded / event.total) * 100;
    _("progressBar").value = Math.round(percent);
    _("status").innerHTML = Math.round(percent) + "% uploaded... please wait";
  }

  function completeHandler(event) {
    _("status").innerHTML = event.target.responseText;
    _("progressBar").value = 0; //wil clear progress bar after successful upload
  }

  function errorHandler(event) {
    _("status").innerHTML = "Upload Failed";
  }

  function abortHandler(event) {
    _("status").innerHTML = "Upload Aborted";
  }
</script>
</body>
</html>

templates/estadoCultivo.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="keywords" content="">
	<meta name="description" content="">

	<title>Información Cultivo | AgroCognitive</title>

	<!-- stylesheet css -->
	<link rel="stylesheet" href="../static/css/bootstrap.min.css">
	<link rel="stylesheet" href="../static/css/font-awesome.min.css">
	<link rel="stylesheet" href="../static/css/nivo-lightbox.css">
	<link rel="stylesheet" href="../static/css/nivo_themes/default/default.css">
	<link rel="stylesheet" href="../static/css/style.css">
	<!-- google web font css -->
	<link href='http://fonts.googleapis.com/css?family=Raleway:400,300,600,700' rel='stylesheet' type='text/css'>

</head>
<body data-spy="scroll" data-target=".navbar-collapse">
	
<!-- navigation -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon icon-bar"></span>
				<span class="icon icon-bar"></span>
				<span class="icon icon-bar"></span>
			</button>
			<a href="{% url 'menuPrincipal' %}" class="navbar-brand smoothScroll">AgroCognitive</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><a href="#contact" class="smoothScroll">Bienvenida, María</a></li>
				<li>
					<div class="hamburger-btn" onclick="openNav()" style="position: relative;top: 25px; left: 30px;">
						<div></div>
						<div></div>
						<div></div>	
					</div>
				</li>
			</ul>
			<div id="mySidenav" class="sidenav">
					  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
					  <a href="#">
					  	<img src="../static/img/cargarImg.png" width="20%" style="margin-right: 10px;">
					  	<h5 style="display: inline-block;">
					  		Cargar imágenes
					  	</h5>
					  </a>
					  <a href="#">
					  	<img src="../static/img/monitorearTerreno.png" width="20%" style="margin-right: 10px;">
					  	<h5 style="display: inline-block;">
					  		Monitorear terrenos
					  	</h5>
					  </a>
					  <a href="#">
					  	<img src="../static/img/monitorearCultivo.png" width="20%" style="margin-right: 10px;">
					  	<h5 style="display: inline-block;">
					  		Monitorear cultivos
					  	</h5>
					  </a>
					  <a href="#">
					  	<img src="../static/img/reporte.png" width="20%" style="margin-right: 10px;">
					  	<h5 style="display: inline-block;">
					  		Generar reportes
					  	</h5>
					  </a>
					  <a href="#">
					  	<img src="../static/img/historico.png" width="20%" style="margin-right: 10px;">
					  	<h5 style="display: inline-block;">
					  		Históricos
					  	</h5>
					  </a>
			</div>
		</div>
	</div>
</div>		

<!-- service section -->
<div id="infoCultivos">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 text-center">
				<h2>Estado de tu cultivo</h2>
			</div>
		</div>
		<div class="row">
			<br>
			<div class="col-md-6 col-sm-6">
				<br>
				<div class="detalles-cultivo">
					<ul class="fa-ul">
						{% if pAfectado > 0 %}
							<li><i class="fa-li fa fa-chevron-right"></i><p>El {{pAfectado}}% de tu cultivo está afectado</p></li>
							<li><i class="fa-li fa fa-chevron-right"></i><p>Respecto al monitoreo anterior se ha incrementado en un 10% la extensión afectada</p></li>
							<li><i class="fa-li fa fa-chevron-right"></i><p>Hemos detectado las siguientes deficiencias en su cultivo:</p></li>
							<br>
							<table rules="rows">
								<thead>
									<th><h4><b>Diagnóstico</b></h4></th>
									<th><h4><b>% de terreno afectado</b></h4></th>
									<th><h4><b>Acción</b></h4></th>
								</thead>
								<tbody>
									<tr>
										<td>
											<h4>Enfermedad de la roya</h4>
										</td>
										<td>
											<h4>{{pRoya}}%</h4>
										</td>
										<td>
											<h4>Aplicar producto en las coordenadas X Y</h4>
										</td>
									</tr>
									<tr>
										<td>
											<h4>Deficiencia moderada de nitrógeno en los suelos</h4>
										</td>
										<td>
											<h4>20%</h4>
										</td>
										<td>
											<h4>Aplicar producto en las coordenadas X Y</h4>
										</td>
									</tr>
								</tbody>
							</table>
						{% else %}
							<li><i class="fa-li fa fa-chevron-right"></i><p>Tu cultivo está totalmente sano. ¡Buen trabajo!</p></li>
						{% endif %}
					</ul>
				</div>
			</div>
			<div class="col-md-5 col-sm-5 col-md-offset-1 wrapper-cultivo2">
				<!--<i class="fa fa-cubes"></i>-->
				<img src="{{ STATIC_URL }}img/{{ diagnostico }}" class="img-responsive" style="margin-top:20px;">
				<div class="icon-bar">
				  <a href="#"><i class="fa fa-search-plus"></i></a> 
				  <a href="#"><i class="fa fa-search-minus"></i></a> 
				  <a href="#"><img class="img-responsive" src="../static/img/grab.png"></a> 
				  <a href="#"><i class="fa fa-expand"></i></a>
				</div>
				<br>
				<ul style="list-style-type: none;">
				    <li style="float: left; margin-right: 25px;">
				    	<span style="float: left; width: 20px; height: 20px; background-color: #ff7f0e; margin: 5px 10px 0px 0px;"></span> <b>Enfermedad y/o plaga</b>
				    </li>
				    <li style="float: left; margin-right: 25px;">
				    	<span style="float: left; width: 20px; height: 20px; background-color: #1f77b4; margin: 5px 10px 0px 0px;"></span> <b>Falta de nutrientes</b>
				    </li>
				</ul>
			</div>
		</div>
	</div>
</div>


<!-- divider section -->
<div class="container">
	<div class="row">
		<br><br>
		<div class="col-md-1 col-sm-1"></div>
		<div class="col-md-10 col-sm-10">
			<hr>
		</div>
		<div class="col-md-1 col-sm-1"></div>
	</div>
</div>

<!-- footer section -->
<footer>
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 text-center">
				<ul class="list-inline">
                    <li>
                        <a target="_blank" href="https://twitter.com/gia_usb" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                    </li>
                    <li>
                        <a target="_blank" href="https://www.youtube.com/channel/UCfNP1LYdgX3qOONWqjGgGLA" class="btn-social btn-outline"><i class="fa fa-fw fa-youtube"></i></a>
                    </li>
                    <li>
                        <a target="_blank" href="https://github.com/GIA-USB" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                    </li>
                </ul>
				<p>Desarrollado por <a href="https://www.smartbasegroup.com" target="_blank">Smartbase Group</a></p>
			</div>
		</div>
	</div>
</footer>


<!-- javascript js -->	
<script src="../static/js/jquery.js"></script>
<script src="../static/js/bootstrap.min.js"></script>	
<script src="../static/js/nivo-lightbox.min.js"></script>
<script src="../static/js/smoothscroll.js"></script>
<script src="../static/js/jquery.nav.js"></script>
<script src="../static/js/isotope.js"></script>
<script src="../static/js/imagesloaded.min.js"></script>
<script src="../static/js/custom.js"></script>
<script type="text/javascript">
	/* Set the width of the side navigation to 250px */
	function openNav() {
	    document.getElementById("mySidenav").style.width = "250px";
	}

	/* Set the width of the side navigation to 0 */
	function closeNav() {
	    document.getElementById("mySidenav").style.width = "0";
	}
</script>

</body>
</html>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="keywords" content="">
	<meta name="description" content="">

	<title>Inicio | AgroCognitive</title>
<!--

Template 2080 Minimax

http://www.tooplate.com/view/2080-minimax

-->
	<!-- stylesheet css -->
	<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
	<link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
	<link rel="stylesheet" href="{{ STATIC_URL }}css/nivo-lightbox.css">
	<link rel="stylesheet" href="{{ STATIC_URL }}css/nivo_themes/default/default.css">
	<link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">
	<!-- google web font css -->
	<link href='http://fonts.googleapis.com/css?family=Raleway:400,300,600,700' rel='stylesheet' type='text/css'>

</head>
<body data-spy="scroll" data-target=".navbar-collapse">
<!-- navigation -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon icon-bar"></span>
				<span class="icon icon-bar"></span>
				<span class="icon icon-bar"></span>
			</button>
			<a href="{% url 'menuPrincipal' %}" class="navbar-brand smoothScroll">AgroCognitive</a>
		</div>
	</div>
</div>		

<!-- service section -->
<div id="login">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 text-center">
				<h2>Agrega inteligencia a tus plantaciones</h2>
			</div>
		</div>
		<div class="row">
			<br>
			<div class="col-md-4 col-sm-4 col-md-offset-4" style="border: 2px solid #444;">
				<form method="POST" encType="multipart/form-data" name="formLogin">
					{% csrf_token %}
					<br>
			        <p>
			          <label>Usuario</label>
			          <div id="wrapper-login">
			            <!--<i class="fa fa-user fa-2x" aria-hidden="true"></i>-->
			            <input class="w3-input" type="text" style="width:90%" required>
			            {{form.identificacion}}
			          </div>
			        </p>
			        <p>
			          <label>Password</label>
			          <div id="wrapper-login">
			              <!--<i class="fa fa-lock fa-2x" aria-hidden="true"></i>-->
			              <input class="w3-input" type="password" style="width:90%" required>
			              {{form.clave}}
			          </div>
			        </p>

			        <p>
			          <input id="milk" class="w3-check" type="checkbox" checked="checked">
			          <label>Recordarme</label>
			        </p>
			        <p class="text-center">
			          <a href=""><label>¿Olvidó su contraseña?</label></a>
			        </p>

			        <p class="text-center">
			          <button class="btn btn-warning" type="submit">Iniciar Sesión</button>
			        </p>

			    </form>
			</div>
			
		</div>
	</div>
</div>

<img src="../static/img/dash-agro.png" style="position: fixed;">

<!-- divider section -->
<div class="container">
	<div class="row">
		<div class="col-md-1 col-sm-1"></div>
		<div class="col-md-10 col-sm-10">
			<hr>
		</div>
		<div class="col-md-1 col-sm-1"></div>
	</div>
</div>

<!-- footer section -->
<footer>
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 text-center">
				<ul class="list-inline">
                    <li>
                        <a target="_blank" href="https://twitter.com/gia_usb" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                    </li>
                    <li>
                        <a target="_blank" href="https://www.youtube.com/channel/UCfNP1LYdgX3qOONWqjGgGLA" class="btn-social btn-outline"><i class="fa fa-fw fa-youtube"></i></a>
                    </li>
                    <li>
                        <a target="_blank" href="https://github.com/GIA-USB" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                    </li>
                </ul>
				<p>Desarrollado por <a href="https://www.smartbasegroup.com" target="_blank">Smartbase Group</a></p>
			</div>
		</div>
	</div>
</footer>


<!-- javascript js -->	
<script src="{{ STATIC_URL }}js/jquery.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>	
<script src="{{ STATIC_URL }}js/nivo-lightbox.min.js"></script>
<script src="{{ STATIC_URL }}js/smoothscroll.js"></script>
<script src="{{ STATIC_URL }}js/jquery.nav.js"></script>
<script src="{{ STATIC_URL }}js/isotope.js"></script>
<script src="{{ STATIC_URL }}js/imagesloaded.min.js"></script>
<script src="{{ STATIC_URL }}js/custom.js"></script>

</body>
</html>